### PR TITLE
Feat/like dislike

### PR DESCRIPTION
**Pull request by SHIKHASINGH1506**
1. User can like and dislike post
2. like count will be displayed on the post

### CODE REVIEW

**Review by jeetbhalani15 — APPROVED** [review]
- postSlice for like dislike works fine
- code is readable
- Nice UI

**Review by sashaboi — APPROVED** [review]
everything works as expected, nice work !

A suggestion. like like count which appears on the like button sort of messes with the styling of the menu , hope you take care of that as a p2 priority thing :)

**Comment by SHIKHASINGH1506** [comment]
> everything works as expected, nice work !
> 
> A suggestion. like like count which appears on the like button sort of messes with the styling of the menu , hope you take care of that as a p2 priority thing :)

I'll modify the style once done with major work

**Comment by SHIKHASINGH1506** [comment]
> * postSlice for like dislike works fine
> 
>     * code is readable
> 
>     * Nice UI

Thanks for review

**Pull request merged**
