### PR TITLE
Feat/user profile

### PR DESCRIPTION
**Pull request by SHIKHASINGH1506**
1. user profile page added
2. edit profile functionality added

### CODE REVIEW

**Review by shraddha15-creator — COMMENTED** [review]
code looks modular and clean

**Review by shraddha15-creator — APPROVED** [review]

**Review by krgarima — APPROVED** [review]
Nice UI and clean code. Good to merge.

**Review by gadgetfather — APPROVED** [review]
- file structure is really good.
- Modal is opening perfectly in mobile and desktop view as well
- Edit functionality is also working as intended.

Great work !

**Comment by SHIKHASINGH1506** [comment]
> * file structure is really good.
> 
>     * Modal is opening perfectly in mobile and desktop view as well
> 
>     * Edit functionality is also working as intended.
> 
> 
> Great work !

Thank you for the review.

**Pull request merged**
